### ISSUE TITLE
Error :  File is not a zip file

### ISSUE THREAD

**Issue by tkrabec** [MarkBaggett/srum-dump#11]
I could not open the specified template file /home/tkrabec/srudb/SRUM_TEMPLATE.xlsx. Check your path and file name.
Error :  File is not a zip file

Same error windows 10 and Centos.

**Comment by tkrabec** [comment]
I re-downloaded the xlsx and it's working.

**Comment by MarkBaggett** [comment]
Sorry I missed your ticket.  I am glad to see you resolved the issue.

Mark

**Comment by tkrabec** [comment]
Not a problem, It was overnight.  Thanks for writing the tool.
Do you know what versions of Server write to the SRU data?

Tim Krabec
tkrabec.com
Bio <http://timkrabec.brandyourself.com/>

**Comment by MarkBaggett** [comment]
I believe it is 2008 and up.

**Comment by tkrabec** [comment]
Its not 08 R2, so it must be those beyond that, thanks

Tim Krabec
tkrabec.com
Bio <http://timkrabec.brandyourself.com/>
