### ISSUE TITLE
Quiet option

### ISSUE THREAD

**Issue by Beercow** [MarkBaggett/srum-dump#14]
Error due to line not being indented.

Traceback (most recent call last):
  File "srum_dump_csv.py", line 361, in <module>
    print("While you wait, did you know ...\n"+ad+"\n")
NameError: name 'ad' is not defined

Traceback (most recent call last):
  File "srum_dump.py", line 328, in <module>
    print("While you wait, did you know ...\n"+ad+"\n")
NameError: name 'ad' is not defined

**Comment by MarkBaggett** [comment]
Thanks for reporting the issue.  I think this is fixed in the version I just pushed.   If you agree and want to close the ticket please do so.  If you still have an issue let me know.   If I don't hear anything more I'll close the ticket.

**Comment by Beercow** [comment]
I’ll take a look tomorrow morning and close the ticket if it’s good to go. Thanks.

**Comment by Beercow** [comment]
Thank you for the prompt update. Everything works.
