### ISSUE TITLE
Not working with current version of openpyxl

### ISSUE THREAD

**Issue by FryJay** [MarkBaggett/srum-dump#15]
Hi Mark, I gave this a try on my Mac using Python 2.7.15 and openpyxl 2.6.1 and ran into some errors related to openpyxl.  Here is the first error it generated:

Traceback (most recent call last):
  File "srum_dump.py", line 8, in <module>
    from openpyxl.writer.write_only import WriteOnlyCell
ImportError: No module named write_only

Which I got around by changing the import to:

from openpyxl.cell import WriteOnlyCell

After that I received this error:

Traceback (most recent call last):
  File "srum_dump.py", line 285, in <module>
    ese_template_table = template_sheet.cell("A1").value
TypeError: cell() takes at least 3 arguments (2 given)

Which I got around by changing the line to:

ese_template_table = template_sheet["A1"].value

I have no idea if it still works as intended though.

**Comment by FryJay** [comment]
I tried it with the python3 branch and ran into the same issue with the import statement but the cell reference issue did not appear.

**Comment by MarkBaggett** [comment]
I fixed the import issue on the Python3 branch.  Thank you very much for reporting it.   For the Python2 version I recommend installing version 2.5 of openpyxl.   If you don't want to do that it should be an easy fix.   Changing "A1" to  row=1,column=1 should do it.   But I intend to merge the two branches soon and the Python2 version will be a thing of the past.  

Please let me know if this fixes the issue for you and if your happy with the response you can close the ticket.  If I don't hear anything back from you I will assume its good and close the ticket.

Mark

**Comment by MarkBaggett** [comment]
Closing.  Please reopen if you continue to have problems.

**Comment by FryJay** [comment]
Sorry for not responding earlier but I tested it again and it works for me now.
