### ISSUE TITLE
srum_dump_csv.exe outputs blank lines between rows

### ISSUE THREAD

**Issue by ItsPaPPy** [MarkBaggett/srum-dump#16]
the xlsx option produces data on each line, but the CSV option outputs data, and then a blank line. see picture

![image](https://user-images.githubusercontent.com/38514524/56140050-f42a2000-5f4e-11e9-9b0d-cf641edf8ee1.png)

**Comment by nrrpinto** [comment]
I also saw the same issue!
@MarkBaggett do you have plan to do anything about it?
Thanks for your time.

**Comment by MarkBaggett** [comment]
Thanks for reporting this issue.  I will take a look at it and try to determine the cause.

**Comment by MarkBaggett** [comment]
Hello.
I have good news and bad news.  The good news is there are no more blank lines.  I released a major rewrite of srum-dump.  srum-dump2 has a GUI, acquires live files and mroe.   I also moved ALL of the csv functionality to a new tool called ese2csv.  It dumps much more than just SRUM files.  It dumps any ese files.  The bad news is I removed calculated fields from the program with the update. Let me know if calculated fields were a critical component and I can look at adding them back in.  Please give ese2csv a try.  You'll find it here.

https://github.com/MarkBaggett/ese-analyst
