### ISSUE TITLE
Suggestion - SID resolution 

### ISSUE THREAD

**Issue by ItsPaPPy** [MarkBaggett/srum-dump#17]
It would be nice to resolve the SID prior to outputting the data.

But i hear doing so can be dangerous in PKI situations where UPN is an external namespace (like the DoD).  As it generates network traffic but also targets the PDC-E role which is single homed by design.  WMI's Win32_UserAccounts sid resolver will hit the PDC-E, so not sure if there is a good way around doing this, or maybe allow as a configurable/opt in option.

**Comment by MarkBaggett** [comment]
If the accounts are local then the SOFTWARE registry hive is used to resolve SIDs.  No network resolution is done at this time.  

Mark
