### ISSUE TITLE
srum_dump_csv.exe outputs formulas instead of results

### ISSUE THREAD

**Issue by nrrpinto** [MarkBaggett/srum-dump#18]
Hi,

As can be seen in the image below, the output of the CSV(in this case the srumNetworkUsage.csv) is returned with the formulas, not with the result. If one wishes to consume the CSV outside of Excel, will not have the result.

![image](https://user-images.githubusercontent.com/29933547/57192602-96c43600-6f32-11e9-9c0b-ba960a785115.png)

**Comment by MarkBaggett** [comment]
All calculations on field are controlled by the template.   The intention of the template is to give you, the analyst, the ability to add and remove or customize fields as you see fit.   The template provided does include some calculations such as sum as examples that can be used.   Those do assume that you are consuming the data in XLSX.   If you are not using the sum function or do not have a tool such as excel that can do additional processing you can remove that column from the template.
