### ISSUE TITLE
'ReadOnlyCell' object has no attribute 'style'

### ISSUE THREAD

**Issue by amm3** [MarkBaggett/srum-dump#2]
@MarkBaggett, this is a great tool!  I do most of my analysis in MacOs or Linux, so my preference was to use your raw python script.  Unfortunately, I'm getting the following `openpyxl` (using version 2.4.1) error:

```
Traceback (most recent call last):
  File "./srum_dump.py", line 327, in <module>
    cell_style = template_sheet.cell(row = 4, column = eachcolumn).style
AttributeError: 'ReadOnlyCell' object has no attribute 'style'
```

It appears (in this version anyway) that the `ReadOnlyCell` class has different properties than the standard `Cell` class.  Simply changing your call to `openpyxl.load_workbook` (line 268) to open the template read-write fixed the issue for me.  Not ideal, but provides for a quick fix.

_(Also, FYI opening read-write appears to be a fairly safe operation if you don't call `wb.save()`.)_

**Comment by MarkBaggett** [comment]
Thanks.   I'll get my Mac and reproduce the issue to make sure I understand the problem.  Then I'll commit that change.   I appreciate the feedback.  

Mark

**Comment by bdooling** [comment]
I can confirm the issue reported by @amm3, as well as the suggested fix.
