### ISSUE TITLE
Issue running on headless linux

### ISSUE THREAD

**Issue by mgreen27** [MarkBaggett/srum-dump#20]
I ran srum_dump on a centos machine I use for analysis thats headless and found with srum_dump2 I had issues when running srum_dump2.py -h with the following error: ModuleNotFoundError: No module named 'tkinter'.

Even after installing tkinter, the issue persisted. I ended up commenting out the line: import PySimpleGUI to see help so I could run the switches (I havent run version 2 before).

Running SRUM with all switches applied worked as expected.

I believe this is caused by srum_dump defaulting to GUI with no variables set. I think you should allow "-h|--help" with no variables and then import PySimpleGUI afterwards.

Matt

**Comment by MarkBaggett** [comment]
That’s a good suggestion.  Thank you.  

Mark

**Comment by MarkBaggett** [comment]
I've moved all of the functionality for command line processing (such as headless) to ese2csv.   
https://github.com/MarkBaggett/ese-analyst
