### ISSUE TITLE
not reading file correctly

### ISSUE THREAD

**Issue by gunner4361** [MarkBaggett/srum-dump#24]
I could not open the specified SRUM file. Check your path and file name.
Error :  ("Unpacked data doesn't match constant value 'b'0\\x00\\x03\\x00'' should be ''ïÍ«\\x89''", 'When unpacking field \'Signature | "ïÍ«\x89 | b"0\\x00\\x03\\x00\\x95\\x10E\\x95\\x02\\x00\\x00\\x00\\x01\\x00\\x01\\x008\\x00\\x01\\x00\\xc8\\x01\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x07\\x00\\x00

**Comment by MarkBaggett** [comment]
Hi Gunner.  I don't have enough information to help you.  What file did you open?   What error message did you get?   How did you acquire the file?  I need some more data before I can help.

**Comment by MarkBaggett** [comment]
Hi @gunner4361 
Can you give me some more data?  Would you mind recording the screen when you run the program and posting it here? 

Here is a screen to gif program.
https://www.cockos.com/licecap/

**Comment by MarkBaggett** [comment]
No response from @gunner4361
