### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by shadikka** [MarkBaggett/srum-dump#25]
Hello,

Thank you for developing this tool. However, as your repository is missing a license file, or any reference to a specific license in the first place, it is strictly speaking forbidden for anybody to use the tool for any purpose besides those outlined in the [GitHub Terms of Service](https://help.github.com/en/github/site-policy/github-terms-of-service) (section D.4 - D.7).

GitHub has both excellent [instructions](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) and a tool for [choosing a license](https://choosealicense.com/) - which conveniently includes details on what it means when you [don't choose a license](https://choosealicense.com/no-permission/).

You mention that parts of srum-dump originate from GRR's [wmi_parser.py](https://github.com/google/grr/blob/master/grr/core/grr_response_core/lib/parsers/wmi_parser.py), which is licensed under the [Apache license 2.0](https://github.com/google/grr/blob/master/LICENSE). Without explicit permission given to you, this likely means that srum-dump should be considered a derivative work and licensed under the same terms.

Furthermore, it is my personal understanding that all contributors to the code should agree to license their contributions under the chosen terms.

As the standard disclaimer, I am not a lawyer - I'm just a person who (full disclosure: and whose employer) would like to use this tool.

**Comment by MarkBaggett** [comment]
License added.
