### ISSUE TITLE
OpenVolume returned error: 30000000

### ISSUE THREAD

**Issue by SuperbSonik** [MarkBaggett/srum-dump#26]
I have tried to extract a SRUDB file by using fget but end up getting this error:
![image](https://user-images.githubusercontent.com/61529488/76179729-d4e75180-61f6-11ea-87d9-25f418d49fb0.png)

this might sound a stupid error but i am really new to this field.... thanks for helping me.

**Comment by MarkBaggett** [comment]
I am not an expert on FGET.  That is an HBGary tool, but such as I have give I thee.

Is this command prompt running as an administrator?  It does require elevated privileges.   

Alternatively you could try running srum-dump with administrative privileges and then click the button that appears in the gui that does it for you.   

Last, you could try it manually using the command that SRUM-DUMP uses when you use the button.  I outline them here.  https://twitter.com/markbaggett/status/1179031762690887680

Best of luck,
Mark
