### ISSUE TITLE
Not Working On Windows 10

### ISSUE THREAD

**Issue by jstore** [MarkBaggett/srum-dump#3]
Hmmm... I get following when I use the default template:

Unable to find table Undocumented Windows 10 Table {97C2CE28-A37B-4920-B1E9-8B76CD341EC5}
I was unable to write the output file. Do you have an old version open? If not this is probably a path or permissions issue.
Error :
Finished!

And I get this when I use the small template:

Traceback (most recent call last):
File "<string>", line 347, in <module>
AttributeError: 'NoneType' object has no attribute 'replace'

This is running on a Windows 10 Enterprise v1607 with a copy of the SRUDB.dat file from the same machine.

**Comment by MarkBaggett** [comment]
The message "Unable to find table Undocumented Windows 10 Table
{97C2CE28-A37B-4920-B1E9-8B76CD341EC5}"   is just a Warning and can be
ignored.   It means that that table doesn't exist in the SRUM file you are
analyzing.   If you would like you can just delete the Undocumented Windows
10 tab from the template file and it wont try to analyze that any more.

The message "I was unable to write the output file. Do you have an old
version open? If not this is probably a path or permissions issue"  occurs
when the program is unable to write the output file you specified on the
command line to disk.   Make sure you have permissions to create the xlsx
file that you specified with the output argument.

The small template isn't intended for production.  It is just an example of
how you can set other attributes up in the template file and change fonts.

Thanks,
Mark Baggett

**Comment by jstore** [comment]
Hi Mark,

I'm running the exe as a local admin and an ouput.xlsx file is created
(almost 2 MB), but when I go to open it in Excel 2016 it says, "The
workbook cannot be opened or repaired by Microsoft Excel because it is
corrupt".

This happens using either template so I thought it was related to the error
messages I was seeing.

-Justin

Justin Store
Security Architect
Michigan Tech University <http://www.mtu.edu/>
Information Technology <http://www.it.mtu.edu/>
906.487.1477

**Comment by jstore** [comment]
Hi Mark,

I've done some more testing with a different SRUDB.dat file and the tools
works as expected.

The original SRUDB.dat file I was using was taken from my Windows 10
machine while using the system. I didn't get any errors about the file
being locked or open so I figured it would work.

The second SRUDB.dat file was taken from a Windows 8.1 machine while using
the system. I had to disable a couple of services to release the hold on
the file.

Assuming you've tested this on Windows 10 SRUDB.dat files, I believe the
issue may be related to copying it while in use. Oddly, Windows didn't have
any issue with me copying it as long as I was a local admin. I've re-copied
the file from my live system and get the same result (corrupt output file).

-Justin

Justin Store
Security Architect
Michigan Tech University <http://www.mtu.edu/>
Information Technology <http://www.it.mtu.edu/>
906.487.1477

**Comment by MarkBaggett** [comment]
Justin,
Thanks for taking my call yesterday and thanks for the feedback.    It has
been tested extensively on Windows 10.

There is some discussion in the comments on this post about how to grab the
file on system where it is locked.   I use Volume Shadow copies but the
Invoke-NinjaCopy utility is a good option also.

Mark

**Comment by jstore** [comment]
Thanks Mark,

I saw that, but didn't think it would be required if the OS didn't complain.

Thanks for following up,

-Justin

Justin Store
Security Architect
Michigan Tech University <http://www.mtu.edu/>
Information Technology <http://www.it.mtu.edu/>
906.487.1477

**Comment by MarkBaggett** [comment]
This and similar issues all appear to be related to corrupt srudb.dat files as a result of file system locks.   I am closing the ticket.  Please let me know if any further attention is required.
