### ISSUE TITLE
Don't open SRUDB.dat File

### ISSUE THREAD

**Issue by Phyxioss** [MarkBaggett/srum-dump#36]
Hello,

I am using your tool for the first time, I exported the srudb.dat file with ftk imager. But when using the tool I got an error like this:

![image](https://user-images.githubusercontent.com/49075451/217942616-32b53e00-4470-4633-8044-a23f1ee7281b.png)

I will be grateful if you could help me. Thanks in advance.

**Comment by MarkBaggett** [comment]
I've tested and confirmed it works properly and when given a valid srum database.  

It's very difficult for me to say what is happening in this case but usually this error is cause by the srum database being corrupted during the export process.  

I have just updated the tool to version 2.5. Perhaps the updates ESE database libraries I am using will resolve this for you.  

Mark
