### ISSUE TITLE
Question about OLE Timestamp

### ISSUE THREAD

**Issue by Fetchered** [MarkBaggett/srum-dump#4]
Hi Mark,
Sorry for using your Github to get a hold of you, but I couldn't find an easy way to get in touch. I have a question regarding the parsing of OLE Timestamps like the ones you parse from the SRUdb. In what format is the actual timestamp when it's processed by your python version of the parser? 

I am trying to do pretty much the same thing in a program I'm writing as you did, but I keep getting a struct.unpack error "unpack requires a string argument of length 8".

It's not directly related to your srum-dump, but do you think you can help?

**Comment by MarkBaggett** [comment]
Hi.  Email me at lo127001 at gmail and I'll help you out.  

Mark

**Comment by MarkBaggett** [comment]
Info sent via email
